default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: pokedex_development
test:
  <<: *default
  database: pokedex_test
production:
  <<: *default
  database: pokedex_production
  username: pokedex
  password: <%= ENV["POKEDEX_DATABASE_PASSWORD"] %>
